services:
  coreai-mcu-prompts:
    build:
      context: .
      target: production
    image: coreai-mcu-prompts
    container_name: coreai-mcu-prompts
    depends_on:
      - coreai-mcu-prompts-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-prompts-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  coreai-mcu-prompts-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: coreai-mcu-prompts
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
