services:
  coreai-mcu-prompts:
    build:
      context: .
      target: production
    image: coreai-mcu-prompts
    container_name: coreai-mcu-prompts
    depends_on:
      - coreai-mcu-prompts-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-prompts-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-devstoreaccount1}

  coreai-mcu-prompts-azurite:
    image: mcr.microsoft.com/azure-storage/azurite